### ISSUE TITLE
Where is the download script

### ISSUE THREAD

**Issue by fengwang** [danielgafni/repalette#36]
The download script 'repalette/utils/download_raw.py' is missing from the repo.

**Comment by efonte** [comment]
repalette/db/utils/download_raw.py

**Comment by fengwang** [comment]
Thx. It might be also good to update this path in the readme.

**Comment by fengwang** [comment]
@danielgafni Please do not forget to update the argument from ' --num_workers 8 ' to ' --num-workers 8 '

**Comment by danielgafni** [comment]
@fengwang thanks for the reminder! Done.
